spring:
  application:
    name: merchant # 程序名字
  kafka: # 配置 kafka
    producer: # 配置生产者信息
      bootstrap-servers: master:9092 # kakfa 地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/receive_coupons?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8901 # 程序端口号
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # 注册中心服务器的地址

